### ISSUE TITLE
Difficulty loading grimpfunc

### ISSUE THREAD

**Issue by tbartholomaus** [fastice/GrIMPNotebooks#3]
Hi, thanks for your work on these modules.

I'm trying to run `NSIDCLoginNotebook.ipynb`, which I've just now cloned into a local directory.  I've created the appropriate `greenlandMapping` environment, as per [instructions](https://github.com/fastice/GrIMPNotebooks/blob/master/NSIDCLoginNotebook.ipynb). However, after conda activating the environment, and ensuring within Jupyter Lab that I'm in a kernel for `greenlandMapping`, I'm unable to execute through the unmodified cells of `NSIDCLoginNotebook.ipynb`.

At the first code cell, "Setup", I'm getting the error
```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [8], line 1
----> 1 import grimpfunc.NASALogin as NASALogin
      2 import panel
      3 import os

ModuleNotFoundError: No module named 'grimpfunc'
```

In the preceding markdown cell, the two markdown cells to "instructions" and "installation" include out-of-date, broken links.

Within my console (a mac), I'm able to see that apparently `grimpfunc` is actually intended to be installed, just as, e.g., `numpy` is.
```
(greenlandMapping) [TCB-MBP-5] anaconda3 $ conda list numpy
# packages in environment at /Users/timb/anaconda3/envs/greenlandMapping:
#
# Name                    Version                   Build  Channel
numpy                     1.23.4           py39hdfa1d0c_1    conda-forge
(greenlandMapping) [TCB-MBP-5] anaconda3 $ conda list grimp*
# packages in environment at /Users/timb/anaconda3/envs/greenlandMapping:
#
# Name                    Version                   Build  Channel
grimpfunc                 0.0.4                    pypi_0    pypi
grimpqgis                 0.0.1                    pypi_0    pypi
(greenlandMapping) [TCB-MBP-5] anaconda3 $
```

This problem persists even after attempting to reinstall `grimpfunc` via `pip install git+https://github.com/fastice/grimpfunc.git@master `, per https://github.com/fastice/GrIMPfunc.
The problem also persists when closing and reloading jupyter lab several times, and restarting the kernel several times.

Thanks for any tips you can offer!

**Comment by fastice** [comment]
Tim,

Thanks for reaching out. Not sure how familiar you are with python, so I will go through some fairly basic troubleshooting steps.

1) It looks like your environments good, but just to be sure start python from the command line and do
 >>> import grimpfunc

If the command returns with no complaints, it’s installed just fine and it’s a jupyter problem. 

It's always a bit of a mystery how jupyter gets all the environment right because several things have to happen. 

A) If you haven’t already done this, from the greenlandMapping environment, execute this command (it’s a one-time thing). 
 python -m ipykernel install --user --name=greenlandMapping

B) With the greenlandMapping environment active, start jupyter with the command
jupyter lab

C) Before you start, ensure you have the notebook's correct kernel. To do this, on the far right corner of the jupyter toolbar, there is a pulldown that lets you select the kernel. You should select “greenlandMapping” as the kernel (this is my guess where the problem is if you followed the other instructions). Usually, once you run the notebook the first time, it will remember in the future. 

If you have done all of these things, it should now work. 

Thanks for the heads up on the links, keeping things current is a challenge (I think one was fine, it should take you back earlier in the notebook, but there was one that yielded a 404).

Please let me know if you continue to have problems.

Hope you have a great rest of your weekend. 

Ian





Ian Joughin 
Polar Science Center 
Applied Physics Lab 
University of Washington 
1013 NE 40th Street 
Seattle, WA 98105-6698 

Data products:  https://nsidc.org/grimp

Data Tools: https://github.com/fastice/GrIMPTools

Phone: 206-221-3177 
Fax:   206-616-3142

**Comment by tbartholomaus** [comment]
Thanks Ian- Well, I'm embarrassed.  I would have sworn that I'd followed your step A: `python -m ipykernel install --user --name=greenlandMapping` but apparently not.  It's all now working as expected.

Thanks for maintaining all these notebooks and tutorials, including that for the IS2 hackweek (https://icesat-2.hackweek.io/tutorials/DataIntegration/dataintegration-2.html).  They're awesome and it's very empowering to be able to draw on these tools so easily.  Open data at its best.
